name: Daily CI

on:
  schedule:
    - cron: '9 8 * * *'   # runs daily at 08:09 UTC
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Run toy
        run: |
          python lp.py 1.50 1.65 1.57
